apiVersion: apps/v1
kind: Deployment
metadata:
  name: slowquery-openapi
  namespace: smart-slow-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slowquery-openapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slowquery-openapi
    spec:
      containers:
        - image: harbor.shopeemobile.com/rds-kube-operator/slowquery-openapi:v1.3.4
          imagePullPolicy: Always
          name: openapi
          command:
            - "/etc/slowquery/slowquery-openapi"
            - "--config=/etc/conf/config.live.toml"
          ports:
            - containerPort: 8098
              name: grpc
              protocol: TCP
          env:
            - name: ENV
              value: "live"
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /etc/conf
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: slowquery-openapi-config
        - name: tmp
          hostPath:
            path: /data/log/openapi_log
            type: DirectoryOrCreate
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slowquery-openapi-config
  namespace: smart-slow-query
data:
  config.live.toml: |-
    # ============================================
    # Server meta
    # ============================================
      server_name = "slow-query-openapi"
      server_env = "live"
      
      # log_level {all,debug,info,warn,error,fatal}"
      log_level = "all"
      
      listen_port = 12345
      
      gin_mode = "debug"
      open_api_token = "fGZN61_zUAxe39_m2VuW"
      db_detail_url = "https://space.shopee.io/console/rds/slow_query/live?dbEnv=%s&clusterUUID=%s&dbNames=%s&startTime=%d&endTime=%d"
      
      # server_shutdown_max_wait_seconds max wait seconds after server shutdown
      server_shutdown_max_wait_seconds = 5
    
    
    # ======================
    # clickhouse Config
    # ======================
      [clickhouse_client_config]
      driver = "http"
      host = "cluster-szinfra-szinfra-clouddba-online.ck.data-infra.shopee.io"
      port = 80
      user = "szinfra_clouddba-cluster_szinfra_szinfra_clouddba_online"
      password = "OhjPBQEDSr5S"
      db_name = "szinfra_clouddba_slow_query"
      max_idle_conn = 10
      max_open_conn = 15
    
    # ======================
    # Server Log config
    # ======================
      [server_log_config]
      log_name = "openapi"
      log_level = "info"
      log_path = "/tmp/log_openapi"
      log_max_file_size = 500 #单位:MB
      log_max_backups = 10
      log_max_age = 10
      log_compress = true
    
    # ======================
    # space config
    # ======================
      [space_config] #apply space account for slow_query
      space_host = "https://space.shopee.io"
      user = "smart_slow_query"
      pass = "smart_slow_query@shopee.com"
    
    # ======================
    # http rate limit config
    # ======================
      [http_rate_limit]
      rate = 10
      capacity = 10
