apiVersion: v1
kind: Service
metadata:
  name: slowquery-analyzer-svc
  namespace: smart-slow-query
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8098
  selector:
    app: slowquery-analyzer
  sessionAffinity: None
  type: ClusterIP
