
# ============================================
# Server meta
# ============================================
server_name = "slow-query"

server_env = "test"

# log_level {all,debug,info,warn,error,fatal}"
log_level = "all"

listen_port = 12345

gin_mode = "debug"

# server_shutdown_max_wait_seconds max wait seconds after server shutdown
server_shutdown_max_wait_seconds = 5


# ======================
# clickhouse Config
# ======================
[clickhouse_client_config]
    driver = "clickhouse"
    host = "10.180.131.45"
    port = 9000
    user = "staging_szinfra_clouddba"
    password = "EdW6KfaIkxjc"
    db_name = "szinfra_clouddba_slow_query_test"
    max_idle_conn = 10
    max_open_conn = 30
    max_life_time = "60s"

# ======================
# Server Log config
# ======================
[server_log_config]
    log_name = "platform"
    log_level = "info"
    log_path = "/tmp/slow-query_log"
    log_max_file_size = 500 #单位:MB
    log_max_backups = 10
    log_max_age = 10
    log_compress = true

# ======================
# space config
# ======================
[space_config]
    space_host = "https://space.test.shopee.io"
    user = "smart_slow_query"
    pass = "smart_slow_query@shopee.com"

# ======================
# cmdb_database config
# ======================
[cmdb_database_config]
    space="https://space.test.shopee.io"
    path = "/apis/cmdb/v2/service/get_dbameta_dbs_details"
    http_method = "GET"
    client_timeout = "5s"

# ======================
# user group config
# ======================
[user_group_config]
    # live 50917    test 26638
    dbass_team_id = 26638
    # live 51353 test 30530
    dba_dod_id = 30530
    # if test_mode=true,
    # 1.all user will be regarded as admin
    test_mode = false

# ======================
# MySQL Config
# ======================
[db_config]
    username = "sz_infra_test"
    password = "TnOa9kDGlnb_T9cIhg8w"
    host = "master.585e6d8af19775e6.mysql.cloud.test.shopee.io"
    port = 6606
    db_name = "shopee_exec_meta_db"
    log_mode = true
    connect_timeout = 20
    max_idle_conns = 10
    max_open_conns = 50
    error_retry = 3

# ======================
# Remote MySQL Config
# ======================
[remote_mysql_access]
    is_test = false
    user = "shopeeroot"
    key = "buhxw6cZ4*YFVkpv"

# ======================
# local cache
# ======================
[local_cache]
    shards = 1024
    expire_time = "10m"
    clean_time = "3m"
    max_cache_size = 1024 #MB

# ======================
# cmdb config
# ======================
[cmdb_config]
#live 7hmsd73RMM
#test J4fww1MbrpJ2
    space_host = "https://space.test.shopee.io"
    dbameta_auth_token = "J4fww1MbrpJ2"

# ============================================
#          DailyRank
# ============================================
[daily_rank_config]
top = 10
order_by = "query_time"
