apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: slowquery-alert
  name: slowquery-alert-svc-node
  namespace: smart-slow-query
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      nodePort: 30189
      protocol: TCP
      targetPort: 12345
  selector:
    app: slowquery-alert
  sessionAffinity: None
  type: NodePort